#+title: Home Assistant Setup Instructions

This will take us through the steps of setting up Home Assistant on Ubuntu Server.


** Prerequisites

To use these instructions, you'll need Ubuntu Server installed on a machine, as well as SSH access (OpenSSH) to the server.

You'll need to install the following tools to use this repository:

#+begin_quote
*Note*: If using my [[https://github.com/shawngerrard/ubuntu-tooling/][ubuntu-tool setup]], these tools should already be installed/configured.
#+end_quote

- [[https://www.gnu.org/software/gawk/][GAWK]]
- [[https://nmap.org/][NMAP]]
- [[https://www.pulumi.com/docs/install/][Pulumi CLI]]
- [[https://cloud.google.com/sdk/docs/install][GCP CLI]]
- [[https://github.com/nvm-sh/nvm?tab=readme-ov-file#installing-and-updating][NVM]]
- [[https://www.npmjs.com/][NPM]] and [[https://nodejs.org/en][Node]]
- [[https://www.typescriptlang.org/][Typescript]]
- [[https://www.npmjs.com/package/ts-node][TS-Node]]

** Specification

I'm running Home Assistant on the following specs:
  - Raspberry Pi model 4b
  - Ubuntu Server 64-bit LTS 22.04
  - 3TB SSD mounted storage volume

*** Future updates:

***** TODO Administer infra stack with Pulumi configuration
***** TODO Change from single node infra to multi-node for high-availability.
***** TODO Replace Raspberry Pi with more powerful server hardware.
***** TODO Replace Ubuntu Server with RedHat Enterprise Linux (RHEL).

** Pulumi authentication

If you haven't already, we must authenticate with Pulumi in order to interact with the Pulumi Cloud API. We can do this a number of different ways - either log in via CLI or use an access token.

#+begin_quote
**Note**: Please refer to the definitions of both organizational and personal access tokens on the [[https://www.pulumi.com/docs/pulumi-cloud/access-management/access-tokens/][Pulumi website]]. This link will also provide the information on how to generate an access token. For the purposes of this guide, we will be creating a _personal access token_.
#+end_quote

#+begin_quote
**Note**: Neither of the options listed below are secure on their own - please refer to Pulumi regarding [[https://www.pulumi.com/blog/using-pulumi-securely/][how to use it securely]].
#+end_quote

*** Update credentials.json with access token

We can update the ~​~/.pulumi/credentials.json~ with the appropriate access token:

#+begin_quote
{
    "current": "https://api.pulumi.com",
    "accessTokens": {
        "https://api.pulumi.com": "<access token>"
    },
    "accounts": {
        "https://api.pulumi.com": {
            "accessToken": "<access token>",
            "username": "<username>",
            "organizations": [
                "<org1>",
                "<org2>"
            ],
            "lastValidatedAt": "2024-04-16T11:35:59.084951264+12:00"
        }
    }
}
#+end_quote

*** Update an environment variable

We could also use the ~PULUMI_ACCESS_TOKEN~ environment variable to store our access token.

** Google Cloud authentication

If you haven't already, we must authenticate with Google in order to interact with the Google Cloud API by setting a project and using a link supplied by Google to optain an access code.

#+begin_src bash
# Set project ID in config
gcloud config set project <YOUR_GCP_PROJECT_ID>

# Obtain a url from Google to log in
gcloud auth login --no-launch-browser
#+end_src

Use the code from the URL provided to obtain an access code and enter the code into the CLI.

** Infrastructure deployment

This guide will deploy ~k3s~ infrastructure to a ~raspberry-pi~ using Pulumi.

*** Scaffold and configuration

We must first create and configure the ~typescript~ pulumi project that will be used to install our infrastructure applications (E.G - ~k3s~, ~helm~, etc).

**** New project

First, we need to create a stack to manage our infrastructure.

We can create and configure our stack by passing in the ~--config~ parameter to the ~pulumi new~ command, as follows:

#+begin_quote
*Note*: Make sure you run the commands below in the correct sub-folder. I.E - ~cd [path/to]/home-assistant/infra-k3s~
#+end_quote

#+begin_src bash
# Create the pulumi project and pass in configuration key/value pairs
pulumi new typescript --name "infra-k3s" \
    --stack "dev" \
    --secret \
    --config="serverKey=$(cat /path/to/private/ssh/key)" \
    --config="serverIp=$(nmap -n -A <server hostname> -oG - | awk '/Up$/{print $2}')" \
    --config="serverUser=<server username>"
#+end_srcg

#+begin_quote
*Note*: This will create a new typescript pulumi project named ~infra-k3s~, a stack named ~dev~, and a configuration file (~Pulumi.dev.yaml~) containing the server SSH key for remote connection as well as the IP address (obtained from ~nmap~) of the server and user account logging in.
#+end_quote

**** Existing projects

First, we must clone our project from the repository:

#+begin_src bash
git clone git@github.com:shawngerrard/home-assistant.git ~/documents/
#+end_src

Then, we must select the ~dev~ stack of our infrastructure project ~infra-k3s~:

#+begin_src bash
cd ~/documents/home-assistant/infra-k3s && pulumi stack select myhome/dev
#+end_src

And also populate the pulumi configuration file for ~infra-k3s~:

#+begin_src bash
cat ~/path/to/ssh/private/key | pulumi config set --secret serverKey
nmap -n -A <server hostname> -oG - | awk '/Up$/{print $2}' | pulumi config set serverIp
pulumi config set serverUser <user name>
#+end_src

Finally, for the projects to compile we must download the code package dependencies from ~npm~ referenced in the project's ~package.json~:

#+begin_src bash
cd ~/documents/home-assistant/infra-k3s && npm install
#+end_src

*** Deployment

With the infrastructure to deploy defined within the project (typically ~index.ts~), we can deploy our ~infra-k3s~ suite.

#+begin_quote
*Note*: Make sure you're in the ~infra-k3s~ sub-folder. ~cd ../infra-k3s~
#+end_quote

#+begin_src bash
# Deploy the pulumi infra-k3s dev stack
pulumi up -y
#+end_src

Once the ~infra-k3s~ stack is deployed, we can deploy the ~app-homeassistant~ application stack.

** Application (Home Assistant) deployment

This guide will deploy the ~home-assistant~ application to the ~k3s~ infrastructure defined in the previous section.

*** Scaffold and configuration

Once the ~infra-k3s~ stack is up, we're ready to deploy our ~app-homeassistant~ application.

**** New project

Next, we need to create a stack to manage our ~home-assistant~ application deployment.

As with the infrastructure stack, we can create and configure our stack by passing in the ~--config~ parameter to the ~pulumi new~ command, as follows:

#+begin_quote
*Note*: Make sure you run the commands below in the correct sub-folder. I.E - ~cd [path/to]/home-assistant/app-homeassistant~
#+end_quote

#+begin_src bash
# Create the pulumi project and pass in configuration key/value pairs
pulumi new typescript --name "app-homeassistant" \
    --stack "dev" \
    --config="org=myhome" \
    --secret \
    --config="serverKey=$(cat /path/to/private/ssh/key)" \
    --config="serverProject=infra-k3s"
#+end_srcg

#+begin_quote
*Note*: This will create a new typescript pulumi project named ~app-homeassistant~, a stack named ~dev~, and a configuration file (~Pulumi.dev.yaml~) containing the pulumi organization ~myhome~, the server SSH key for remote connection, and the name of the infrastructure project we created earlier.
#+end_quote

**** Existing project

Next, using the code repository we cloned from Github earlier, we must select the ~dev~ stack of our application deployment project ~app-homeassistant~:

#+begin_src bash
cd ~/documents/home-assistant/app-homeassistant && pulumi stack select myhome/dev
#+end_src

Then, populate the pulumi configuration file for ~app-homeassistant~:

#+begin_src bash
cat ~/path/to/ssh/private/key | pulumi config set --secret serverKey
pulumi config set org myhome
pulumi config set serverProject infra-k3s
#+end_src

Finally, for the projects to compile we must download the code package dependencies from ~npm~ referenced in the project's ~package.json~:

#+begin_src bash
cd ~/documents/home-assistant/app-homeassistant && npm install
#+end_src

*** Deployment

With the applications to deploy defined within the project (typically ~index.ts~), we can deploy our ~app-homeassistant~ suite.

#+begin_quote
*Note*: Make sure you're in the ~app-homeassistant~ sub-folder. ~cd ../app-homeassistant~
#+end_quote

#+begin_src bash
# Deploy the pulumi dev stack
pulumi up -y
#+end_src

** Integrations (Google Cloud) deployment

This guide will outline how to deploy the integrations to ~home-assistant~ within a ~gcp~ project.

*** Enable services

First, we must enable the required integration services within ~gcp~:

#+begin_src bash
# Enable the smart device management api in the gcp api library
gcloud services enable smartdevicemanagement.googleapis.com

# Enable the cloud pub/sub api in the gcp api library
gcloud services enable pubsub.googleapis.com
#+end_src

** Install Docker

To start with, we'll be running our Home Assistant application in a Docker container.

To install Docker, consult the official Docker [[https://docs.docker.com/engine/install/ubuntu/][installation instructions]] for Ubuntu.

For reference: I've installed Docker using their ~apt~ repository.

#+begin_quote
This Docker installation requires root privileges to run Docker containers. To run Docker containers as a non-root user, follow the official Docker [[https://docs.docker.com/engine/install/linux-postinstall/][Linux post-installation instructions]].
#+end_quote

#+begin_quote
Any OCI (Open Container Initiative) compatible runtime can be used to run a Home Assistant container.
#+end_quote

*** Future updates:

***** TODO Replace Docker with a single-node Kubernetes cluster.
***** TODO Install RedHat OpenShift (RHOS) over the top of Kubernetes to better orchestrate the platform.

** Create a Home Assistant Docker container

With Docker installed, we can start Home Assistant in an OCI (Open Container Initiatie) container.

#+begin_src sh :shebang "#!/bin/bash" :notangle
docker run -d \
  --name homeassistant \
  --privileged \
  --restart=unless-stopped \
  -e TZ=MY_TIME_ZONE \
  -v /PATH_TO_YOUR_CONFIG:/config \
  -v /run/dbus:/run/dbus:ro \
  --network=host \
  ghcr.io/home-assistant/home-assistant:stable
#+end_src

#+begin_quote
- /PATH_TO_YOUR_CONFIG points at the folder where you want to store your configuration and run it. Make sure that you keep the :/config part.

- MY_TIME_ZONE is a tz database name, like TZ=America/Los_Angeles.

- D-Bus is optional but required if you plan to use the Bluetooth integration.
#+end_quote

#+begin_src sh :shebang "#1/bin/bash" :tangle
docker run -d \
  --name homeassistant \
  --privileged \
  --restart=unless-stopped \
  -e TZ=Pacific/Auckland \
  -v /mnt/data:/config \
  -v /run/dbus:/run/dbus:ro \
  --network=host \
  ghcr.io/home-assistant/home-assistant:stable
#+end_src

** Access the Home Assistant dashboard

Once the Docker container is up and running, the Home Assistant dashboard will be accessible using ~http://<host name/host ip network address>:8123/~.

