* Application deployment (keycloak)

This section will deploy the ~keycloak~ application to the ~k3s~ infrastructure defined in the _Infrastructure deployment_ section.

#+begin_quote
*Note*: Make sure you run the commands in this section in the correct sub-folder. I.E - ~cd [path/to]/home-assistant/app-keycloak~
#+end_quote

** Configuration

Once the [[../app-homeassistant/README.org][app-homeassistant]] stack is up, we're ready to deploy our ~app-keycloak~ application.

Using the code repository we cloned from Github in the _Infrastructure deployment_ section, we must select the ~myhome~ org and ~dev~ stack of our application deployment project ~app-keycloak~:

#+begin_src bash
cd ~/documents/home-assistant/app-keycloak && pulumi stack select myhome/dev
#+end_src

The code attempts to obtain stack references from the ~myhome/infra-k3s/dev~ stack. To enable Pulumi to achieve this, we need to populate the pulumi configuration file for ~app-keycloak~:

#+begin_src bash
cd ~/documents/home-assistant/app-homeassistant
pulumi config set org $(pulumi org get-default)
pulumi config set serverProject infra-k3s
pulumi config set certManagerProject app-certmanager
cat ~/path/to/ssh/private/key | pulumi config set --secret serverKey
#+end_src

For the project to compile we must download the code package dependencies from ~npm~ referenced in the project's ~package.json~:

#+begin_src bash
cd ~/documents/home-assistant/app-keycloak && npm install
#+end_src

** Deployment

We should now be able to bring up the ~app-keycloak~ services.

#+begin_src bash
pulumi up -y
#+end_src
